#! /usr/bin/python3
import re

#Hangul to English matching
names = {
	"Good.Morning":re.compile(r"좋은아침"),
	"World.News":re.compile(r"지구촌뉴스"),
	"Hi.Korean":re.compile(r"안녕 우리말"),
	"Winning.Beauty.Salon.de.Rim":re.compile(r"수상한 미용실 살롱 드림"),
	"Reporter.K":re.compile(r"취재파일 K"),
    "Moms.Spring.Day":re.compile(r"엄마의 봄날"),
    "Backpack.Travels":re.compile(r"걸어서 세계속으로"),
	"New.Human.Market":re.compile(r"인간시장"),
	"Hangul.Day.Special":re.compile(r"한글날 특집"),
	"Sunday.Special.Documentary":re.compile(r"일요특선 다큐멘터리"),
	"Alchemist":re.compile(r"연금술사"),
	"Special.Docu":re.compile(r"특집\s?다큐"),
#	"Special.Docu.Didnt.Send.the.Letter":re.compile(r"특집다큐 보내지 못한 편지"),
	"Indelible.Digital.Stigma":re.compile(r"지워지지 않는 디지털 낙인"),
	"Jeon.Hyun.Moo.Show":re.compile(r"전무후무 전현무 쇼"),
	"She.is.Wow":re.compile(r"우와한 녀"),
	"World.Culture.Travel":re.compile(r"세계문명여행"),
	"Global.Information.Show.People.around.the.World":re.compile(r"글로벌 정보쇼 세계인"),
	"Because.its.the.First.Time":re.compile(r"처음이라서"),
	"Live.Connection":re.compile(r"라이브 커넥션"),
	"Leaving.by.Train.World.Travel":re.compile(r"기차로떠나는 세계여행"),
	"How.to.Fit":re.compile(r"하우투핏"),
	"Fox.looks.in.between.Radio":re.compile(r"속 보이는 라디오 여우사이"),
	"Current.Affairs.Magazine":re.compile(r"시사매거진"),
	"Animal.Kingdom":re.compile(r"동물의 왕국"),
#	"Special.Docu.Rediscovery.of.the.Forest":re.compile(r"특집다큐 숲의 재발견"),
	"The.20th.Busan.International.Fiml.Festival.Opening.Ceremony":re.compile(r"제20회 부산국제영화제 개막식"),
	"Emperor.of.the.Sea":re.compile(r"해신"),
	"The.Village":re.compile(r"마을"),
	"Six.Flying.Dragons":re.compile(r"육룡이 나르샤"),
	"Sassy.Go.Go":re.compile(r"발칙하게 고고"),
	"Glamorous.Temptation":re.compile(r"화려한 유혹"),
	"Today.Meet.The.Future":re.compile(r"오늘 미래를 만나다"),
	"Top.Band":re.compile(r"탑 밴드"),
	"Power.of.Asian.Cinema":re.compile(r"아시아 영화의 힘"),
	"South.and.North.Spirit.from.the.same.Pot":re.compile(r"남심북심 한솥밥"),
	"Korean.Cuisine":re.compile(r"한식, 세계를 품다"),
	"Lee.Yeon.Boks.Delicious.Banquet":re.compile(r"이연복 셰프의 맛있는 잔치"),
	"Happy.Moments.of.my.Life":re.compile(r"내 생애 행복한 순간"),
	"Iljimae":re.compile(r"일지매"),
	"Indiegame":re.compile(r"인디게임"),
	"Curious.Sunday.Jang.Young.Shil.Show":re.compile(r"궁금한 일요일 장영실쇼"),
	"Inside.the.Cultural.Heritage":re.compile(r"문화재 인사이드"),
	"The.Capable.Ones":re.compile(r"능력자들"),
	"2nd.World.War.70.Year.Anniversary.Docu.Project":re.compile(r"2차대전 종전 70주년 기획 다큐"),
	"Special.Nature.Docu.Green.Planet":re.compile(r"특집 자연다큐 - 그린 플래닛"),
	"Dream.and.Challenge":re.compile(r"청년 대한민국 청춘응원콘서트 꿈꾸라 도전하라"),
	"Mother.Do.Fine":re.compile(r"엄마니까 괜찮아"),
	"True.Beer.Story":re.compile(r"갓구라 트루 맥주스토리"),
	"True.Police.Story":re.compile(r"갓구라 트루 경찰 스토리"),
	"True.Troubled.Story":re.compile(r"갓구라 트루 고민 스토리"),
	"Love.in.Myanmar":re.compile(r"러브 인 미얀마"),
	"Back.Home.after.70.Years":re.compile(r"홋카이도 강제징용\s?자 70년만의 귀향"),
	"K.Bab.Star.Whos.Your.Mama":re.compile(r"K밥스타( -)? 어머(니가|님이) 누구니"),
	"Global.Find.Dad":re.compile(r"글로벌 아빠찾아 삼만리"), # find better translation
	"Korea.Cultural.Heritage":re.compile(r"문화유산 코리아"),
	"Parents.Life.a.Mirror":re.compile(r"부모 생활 보감"),
	"New.Star.King":re.compile(r"(뉴|NEW) 스타킹"),
	"Younha.a.Trip.to.Japan":re.compile(r"윤하\, 일본을 담다"),
	"Great.Inheritance":re.compile(r"위대한 유산"),
	"Idol.Star.Athletics.Championshop":re.compile(r"아이돌스타 육상 씨름 농구 풋살 양궁 선수권대회"),
	"World.Gourmet.War":re.compile(r"세계 미식대전"), #???
	"20x20.Young.People":re.compile(r"20X20 청년"),
	"Miko.On.Air.Casting.Day":re.compile(r"미코 온에어 캐스팅데이"),
	"Wild.Diary":re.compile(r"야생일기"),
	"2015.Korea-China.Joint.Project.New.Hallyu.Era":re.compile(r"한중공동기획 2015 신한류시대"),
	"Your.Curious.Story.Y":re.compile(r"궁금한 이야기 Y"),
	"Japan.is.Delicious":re.compile(r"일본은 맛있다"),
	"Road.FC.Young.Guns":re.compile(r"로드 FC 영건스"),
	"Luxury.Tour":re.compile(r"럭셔리 투어"),
	"Lets.Go.Japan.Train.Travel":re.compile(r"출발 일본 기차여행"),
	"Hokkaidos.Seasonal.Beauty":re.compile(r"홋카이도 계절의 아름다움"),
	"Japan.Izakaya.Top.100":re.compile(r"일본 이자카야 TOP 100"),
	"Find.Japanese.Restaurants.GoGoGo":re.compile(r"일본 맛집찾아 고고고"),
	"My.Fantastic.Funeral":re.compile(r"나의 판타스틱한 장례식"),
	"Surplus.of.Hitchhiking":re.compile(r"잉여들의 히치하이킹"),
	"There.are.no.Bad.Dogs.in.the.World":re.compile(r"세상에 나쁜 개는 없다"),
	"CPR.Song":re.compile(r"심폐소생송"),
	"DMC.Festival.Final.Concert":re.compile(r"DMC 페스티벌 파이널 콘서트"),
	"Channel.Seohyun":re.compile(r"채널 서현"),
	"Duet.Song.Festival":re.compile(r"듀엣가요제"),
	"People":re.compile(r"사람과 사람들"),
	"Consumer.Report":re.compile(r"소비자\s?리포트"),
	"Would.You.Like.a.Japanese.Hot.Spring.Tour":re.compile(r"가고싶은 일본온천여행"),
	"VJ.on.the.Scene":re.compile(r"VJ 특공대"),
	"House.of.Thought":re.compile(r"창의인재 프로젝트 생각의 집"),
	"Accompanied.By":re.compile(r"동행"),
	"Food.Perspectives.for.New.Humans":re.compile(r"신인류 식품관"),
	"Doppel.Singer.Concert":re.compile(r"도플싱어 가요제"),
	"How.to.Become.Rich":re.compile(r"협동프로젝트 신 부자수업"),
	"I.am.a.Natural.Person":re.compile(r"나는 자연인이다"),
	"Real.Docu.Soom":re.compile(r"리얼다큐 숨"),
	"Mocudrama.Sign":re.compile(r"모큐드라마 싸인"),
	"Link.Software.World":re.compile(r"링크 소프트웨어 세상"),
	"Parent.Issues.like.N":re.compile(r"부모 이슈 N맘"),
	"Real.Theater":re.compile(r"리얼극장"),
	"Cruel.Palace.War.of.Flowers":re.compile(r"궁중잔혹사 꽃들의 전쟁"),
	"Happy.Guidance":re.compile(r"행복한 지도"),
	"Lee.Oh.Ryungs.100.Years.of.Study":re.compile(r"이어령의 백년서재"),
	"Global.Family":re.compile(r"글로벌 가족정착기"),
	"Live.Info.Show":re.compile(r"생생정보"),
	"Live.Late.Night.Forum":re.compile(r"심야토론"),
	"New.Story":re.compile(r"뉴스토리"),
	"Extreme.Job":re.compile(r"극한 직업"),
	"MBC.Docu.Special":re.compile(r"MBC 다큐스페셜"),
	"Human.Docu.Sanoramyun":re.compile(r"휴먼다큐 사노라면"),
	"Human.Docu.People.Are.Good":re.compile(r"휴먼다큐 사람이 좋다"),
	"Drama.Special":re.compile(r"^KBS 드라마 스페셜"),
	"SBS.Special":re.compile(r"SBS 스페셜"),
	"Global.Docu.Life.Story":re.compile(r"글로벌 다큐멘터리 (\- )?라이프 스토리"),
	"Global.Project.Sharing":re.compile(r"글로벌 프로젝트 나눔"),
	"Docu.Three.Days":re.compile(r"다큐멘터리 3일"),
	"Chase.60min":re.compile(r"추적 60분"),
	"How.to.Live.and.Eat.Well.Did.You.Have.a.Meal":re.compile(r"잘먹고 잘사는법 식사하셨어요"),
	"The.Day.in.History":re.compile(r"역사저널 그날"),
	"EBS.Special.Project":re.compile(r"스페셜 프로젝트"),
	"PD.Notebook":re.compile(r"PD수첩"),
	"Oh.My.God":re.compile(r"오 마이 갓"),
	"Gentleman.League":re.compile(r"젠틀맨리그"),
	"Want.To.Know":re.compile(r"그것이 알고\s?싶다"),
	"The.Insight":re.compile(r"명견만리"),
	"Screen.***REMOVED***.The.Mountain":re.compile(r"영상앨범 산"),
	"Mysteries.of.the.Human.Body":re.compile(r"생로병사의 비밀"),
	"In.Depth.Window":re.compile(r"시사기획 창"),
	"The.Merchant.Gaekju.2015":re.compile(r"장사의 신 객주 2015"),
	"History.Channel.e":re.compile(r"역사채널e"),
	"Docu.Gonggam":re.compile(r"다큐 공감"),
	"To.See.the.World.Through.Your.Eyes":re.compile(r"세계의 눈"),
	"Macho.House":re.compile(r"수컷의 방을 사수하라"),
	"The.Secret.Readers.Club":re.compile(r"비밀독서단"),
	"KBS.Docu.One":re.compile(r"다큐 1"),
	"MBC.100min.Discussion":re.compile(r"100분 토론"),
	"Only.One.Earth":re.compile(r"하나뿐인 지구"),
	"A.Marvellous.Story.Real.Situation":re.compile(r"기막힌 이야기 실제상황"),
	"My.Neighbor.Charles":re.compile(r"이웃집 찰스"),
	"Atlas":re.compile(r"세계견문록 아틀라스"),
	"Theme.Travels.Around.the.World":re.compile(r"세계테마기행"),
	"Korea.Travel":re.compile(r"한국기행"),
	"All.of.the.World.Docu":re.compile(r"세상의 모든 다큐"),
	"Korea.Cuisine.and.Dining":re.compile(r"한국인의 밥상"),
	"Knowledge.Channel.e":re.compile(r"지식채널 e"),
#	"MBC.Docu.Prime":re.compile(r"MBC 다큐프라임"),
	"The.Best.Recipes":re.compile(r"최고의 요리\s?비결"),
	"Humanities.Lecture":re.compile(r"인문학 특강"),
	"Docu.Prime":re.compile(r"다큐\s?프라임"),
	"Documentary.Today":re.compile(r"다큐 오늘"),
	"Real.Story.Eye":re.compile(r"리얼스토리 눈"),
	"Goddess.of.Fire":re.compile(r"불의 여신 정이"),
	"Noble.My.Love":re.compile(r"고결한 그대"),
	"Lee.Kyung.Kyoos.Real.Camera":re.compile(r"이경규의 진짜카메라"),
	"For.The.Very.First.Time":re.compile(r"난생처음"),
	"Moranbong.Club":re.compile(r"모란봉 클럽"),
	"Show.Me.A.Receipt":re.compile(r"영수증을 보여줘"),
	"Waving.Apron":re.compile(r"앞치마 휘날리며"),
	"The.Secret.of.Keu.Keu.Island":re.compile(r"크크섬의 비밀"),
	"Prime.Minister.and.I":re.compile(r"총리와 나"),
	"Yoo.Se.Yoons.Art.Video":re.compile(r"유세윤의 아트비디오"),
	"Crime.Squad":re.compile(r"강력반"),
	"Dream":re.compile(r"^드림"),
	"D-Day":re.compile(r"디데이"),
	"How.I.Survived":re.compile(r"살아보니 어때"),
	"Immutable.Law.of.Love.S07.Bad.Boys":re.compile(r"연애불변의법칙 시즌7 나쁜남자"),
	"No.More.Show":re.compile(r"지상렬의 (노|No)모쇼"),
	"What.Star.Did.You.Come.From":re.compile(r"넌 어느 별에서 왔니"),
	"Love.Story.in.Harvard":re.compile(r"러브스토리 인 하버드"),
	"Super.Concert":re.compile(r"슈퍼 콘서트"),
	"Prime.Concert":re.compile(r"프라임\s?콘서트"),
	"Lets.Go.Time.Expedition":re.compile(r"렛츠고 시간탐험대"),
	"Arang.and.the.Magistrate":re.compile(r"아랑사또전"),
	"Padam.Padam.The.Sound.of.His.and.Her.Heartbeats":re.compile(r"빠담빠담\-그와 그녀의 심장 박동소리"),
	"International.Apartment":re.compile(r"국제아파트"),
	"Simple.Folks":re.compile(r"간편밥상"), # check for correct name later
	"Sweet.18":re.compile(r"낭랑18세"),
	"No.Way.I.am.an.Adult":re.compile(r"어쩌다 어른"),
	"Masters.Sun":re.compile(r"주군의 태양"),
	"Shut.Up.Flower.Boy.Band":re.compile(r"닥치고 꽃미남밴드"),
	"Reply.1997":re.compile(r"응답하라 1997"),
	"A.Witchs.Romance":re.compile(r"마녀의 연애"),
	"Headliner":re.compile(r"헤드라이너"),
	"Secret":re.compile(r"비법"),
	"Box":re.compile(r"박스"),
	"New.Journey.To.The.West":re.compile(r"신서유기"),
	"How.Do.I.Look":re.compile(r"나 어때"),
	"Seoul.Drama.Awards":re.compile(r"서울 드라마 어워즈"),
	"Incheon.Pentaport.Rock.Festival":re.compile(r"인천 펜타포트 락 페스티벌"),
	"The.42nd.Korean.Broadcasting.Awards":re.compile(r"제42회 한국방송대상 시상식"),
	"You.Are.So.Pretty":re.compile(r"당신 참 예쁘다"),
	"Mom.":re.compile(r"^엄마\."),
	"2015.Seoul.Drama.Awards.International.Dramas":re.compile(r"2015 서울드라마어워즈 해외드라마걸작선"),
	"Age.is.just.a.Number":re.compile(r"내 나이가 어때서"),
	"The.Friends.in.Croatia":re.compile(r"더프렌즈 in 크로아티아"),
	"Everything.Will.Be.Okay":re.compile(r"다 잘될 거야"),
	"The.Racer":re.compile(r"(질주본능 )?(더\s?레이서|The Racer)"),
	"Baek.Jong.Wons.3.Great.Emperors":re.compile(r"백종원의 3대\s?천왕"),
	"Twenty.Again":re.compile(r"두\s?번째 스무살"),
	"Drama.Festival":re.compile(r"드라마 페스티벌"),
	"Scandal.A.Schocking.and.Wrongful.Incident":re.compile(r"^스캔들"),
	"Goddess.of.Marriage":re.compile(r"결혼의 여신"),
	"Princess.Aurora":re.compile(r"오로라 공주"),
	"Ugly.Alert":re.compile(r"못난이 주의보"),
	"Oh.My.Girl.Cast":re.compile(r"오마이걸 캐스트"),
	"A.Tale.of.Two.Sisters":re.compile(r"지성이면 감천"),
	"To.Be.Continued":re.compile(r"투 비 컨티뉴드"),
	"To.You.Project.Finding.Sugarman":re.compile(r"투유 프로젝트 (\-\s)?슈가맨을 찾아서"),
	"Ace":re.compile(r"에이스"),
	"Among.Chefs":re.compile(r"셰프끼리"),
	"The.Heirs":re.compile(r"상속자들"),
	"Medical.Top.Team":re.compile(r"메디컬 탑팀"),
	"Marry.Him.If.You.Dare":re.compile(r"미래의 선택"),
	"Thank.You":re.compile(r"고맙습니다"),
	"City.of.Glass":re.compile(r"유리의 성"),
	"Pretty.Man":re.compile(r"예쁜 남자"),
	"One.Warm.Word":re.compile(r"따뜻한 말 한마디"),
	"Kings.Family":re.compile(r"왕가네 식구들"),
	"A.Little.Love.Never.Hurts":re.compile(r"사랑해서 남주나"),
	"The.Woman.Who.Married.Three.Times":re.compile(r"세\s?번 결혼하는 여자"),
	"Serial.Shopping.Family":re.compile(r"연쇄\s?쇼핑\s?가족"),
	"Passionate.Love":re.compile(r"열애"),
	"Nine.Tailed.Fox":re.compile(r"구미호외전"),
	"Tree.of.Heaven":re.compile(r"천국의 나무"),
	"Cinderellas.Sister":re.compile(r"신데렐라 언니"),
	"Cheo.Yong":re.compile(r"처용"),
	"Hold.My.Hand":re.compile(r"내 손을 잡아"),
	"Empress.Ki":re.compile(r"기황후"),
	"Beyond.the.Clouds":re.compile(r"태양은 가득히"),
	"Cunning.***REMOVED***.Lady":re.compile(r"앙큼한 돌싱녀"),
	"Rising.UP10TION":re.compile(r"라이징\! 업텐션"),
	"Gods.Gift.14.Days":re.compile(r"신의 선물 \- 14일"),
#	"Three.Days":re.compile(r"쓰리데이즈"),
	"Kang.Goos.Story":re.compile(r"강구이야기"),
	"Please.Marry.Me":re.compile(r"결혼해주세요"),
	"The.Virtual.Bride":re.compile(r"별난 며느리"),
	"Come.Jang.Bo.Ri":re.compile(r"왔다\! 장보리"),
	"Jeong.Do.Jeon":re.compile(r"정도전"),
	"DMZ.Peace.Concert":re.compile(r"DMZ 평화콘서트"),
	"I.am.Korea":re.compile(r"국민대합창\s?\-?나는 대한민국"),
	"Angel.Eyes":re.compile(r"엔젤아이즈"),
	"Everybody.Kimchi":re.compile(r"모두 다 김치"),
	"Shining.Romance":re.compile(r"빛나는 로맨스"),
	"Get.it.Beauty":re.compile(r"Get it Beauty"),
	"Yetti.TV":re.compile(r"예띠 TV"),
	"Immortal.Songs":re.compile(r"불후의 명곡"),
	"I.am.Kim.So.Jung":re.compile(r"아임 김소정"),
	"Rude.Miss.Young.Ae":re.compile(r"막돼먹은\s?영애씨"),
	"18.Seconds":re.compile(r"18초"),
	"A.New.Leaf":re.compile(r"개과천선"),
	"Big.Man":re.compile(r"빅맨"),
	"Miss.Mermaid":re.compile(r"인어\s?아가씨"),
	"Something.About.1%":re.compile(r"1\%의 어떤 것"),
	"Doctor.Stranger":re.compile(r"닥터 이방인"),
	"You.Stole.My.Heart":re.compile(r"난 네게 반했어"),
	"Triangle":re.compile(r"트라이앵글"),
	"Six.Flying.Dragons":re.compile(r"육룡이 나르샤"),
	"Yong.Pal":re.compile(r"용팔이"),
	"I.Have.a.Lover":re.compile(r"애인 있어요"),
    "The.Stars.are.Shining":re.compile(r"별이 되어 빛나리"),
#	"TV.Novel.The.Stars.are.Shining":re.compile(r"TV소설 별이 되어 빛나리"),
	"My.Love.Enemy":re.compile(r"내 사랑\,? 웬수"),
	"The.Eccentric.Daughter-in-Law":re.compile(r"시어머니 길들이기"),
	"I.Ask.of.You.Mom":re.compile(r"부탁해요 엄마"),
	"Their.Fortress":re.compile(r"그들의 성채"),
	"She.was.Pretty":re.compile(r"그녀는\s?예뻤다"),
	"My.Daughter.Geum.Sa.Wol":re.compile(r"내 딸\,? 금사월"),
	"Two.Mothers":re.compile(r"뻐꾸기 둥지"),
	"Human.Theater":re.compile(r"인간극장"),
	"Melody.of.Love":re.compile(r"사랑은 노래를 타고"),
	"Mrs.Cop":re.compile(r"미세스\s?캅"),
	"CJ.Hellomobile.Surprise":re.compile(r"CJ 헬로모바일 슈퍼레이스"),
	"Doll.House":re.compile(r"인형의 집"),
	"My.Dear.Cat":re.compile(r"고양이는 있다"),
	"Mothers.Garden":re.compile(r"엄마의 정원"),
	"SuperClassic":re.compile(r"슈퍼클래식"),
	"MAPS":re.compile(r"(느리게 달려야 보이는 것들 )?MAPS"),
	"Endless.Love":re.compile(r"끝없는 사랑"),
	"Trot.Lovers":re.compile(r"트로트의 연인"),
	"Gunman.in.Joseon":re.compile(r"조선 총잡이"),
	"Phoenix":re.compile(r"불새"),
	"Magic.Eye":re.compile(r"매직아이"),
	"Fated.to.Love.You":re.compile(r"운명처럼 널 사랑해"),
	"High.School.Love.On":re.compile(r"하이스쿨\-러브온"),
	"Gadget":re.compile(r"가제트"),
	"Tundra.Show":re.compile(r"툰드라 쇼"),
	"Hot.Clip.Ranking":re.compile(r"남자들의 동영상 랭크쇼"),
	"Can.We.Love.Again":re.compile(r"우리 다시 사랑할까요"),
	"Its.Okay.Its.Love":re.compile(r"괜찮아\, 사랑이야"),
	"Mama":re.compile(r"마마"),
	"Hotel.King":re.compile(r"호텔킹"),
	"Bad.Guy":re.compile(r"나쁜 남자"),
	"The.Night.Watchman":re.compile(r"야경꾼 일지"),
	"The.Spring.Day.of.My.Life":re.compile(r"내 생애 봄날"),
	"My.Lovely.Girl":re.compile(r"내겐 너무 사랑스러운 그녀"),
	"Wild.Romance":re.compile(r"난폭한 로맨스"),
	"Salamander.Guru.and.the.Gang":re.compile(r"도롱뇽\s?도사와 그림자 조작단"),
	"You.are.All.Surrounded":re.compile(r"너희들은 포위됐다"),
	"CLCs.Beautiful.Mission":re.compile(r"CLC의 뷰티풀 미션"),
	"Last":re.compile(r"라스트"),
	"Guide":re.compile(r"가이드"),
	"City.Hall":re.compile(r"시티홀"),
	"Almaengi":re.compile(r"알맹이"), # change to english name later
	"SNSD.Hello.Baby":re.compile(r"소녀시대\s?헬로베이비"),
	"Loveholic":re.compile(r"러브홀릭"),
	"Unstoppable.High.Kick":re.compile(r"거침없이 하이킥"),
	"Channel.SNSD":re.compile(r"(채널|Channel)\s?(소녀시대|소시|SNSD)"),
	"TV.Novel.Dear.My.Sister":re.compile("TV소설 복희누나"),
	"The.Kingdom.of.Wind":re.compile(r"바람의 나라"),
	"The.Iron.Empress":re.compile(r"천추태후"),
	"Time.Between.Dog.And.Wolf":re.compile(r"개와 늑대의 시간"),
	"Angry.Wives":re.compile(r"아내가 뿔났다"),
	"Manny":re.compile(r"매니"),
	"The.Delicious.One.Shot":re.compile(r"더 맛있는 원샷"),
	"Cinderella.Man":re.compile(r"신데렐라 맨"),
	"Can.Anyone.Love":re.compile(r"사랑은 아무나 하나"),
	"Only.My.Love":re.compile(r"나만의 당신"),
	"I.Do.I.Do":re.compile(r"아이두 아이두"),
	"Love.Letter":re.compile(r"러브레터"),
	"Spider":re.compile(r"거미"),
	"Since.We.Met":re.compile(r"그대를 알고부터"),
	"Invitation":re.compile(r"초대"),
	"Boys.Over.Flowers":re.compile(r"꽃보다 남자"),
	"Walk.the.Order":re.compile(r"주문을 걸어"),
	"War.of.Money":re.compile(r"쩐의\s?전쟁"),
	"Tears.of.the.Dragon":re.compile(r"용의 눈물"),
	"Gloria":re.compile(r"글로리아"),
	"Friend.Our.Legend":re.compile(r"친구\.?\,?\s?우리들의 전설"),
#	"My.Girl":re.compile(r"마이걸"),
	"Assembly":re.compile(r"[어|에]셈블리"),
	"Goodbye.Solo":re.compile(r"굿바이 솔로"),
	"Sorry.I.Love.You":re.compile(r"미안하다 사랑한다"),
	"Summer.Scent":re.compile(r"여름향기"),
	"Oh.My.Lady":re.compile(r"오\! 마이 레이디"),
	"Delightful.Girl.Choon.Hyang":re.compile(r"쾌걸춘향"),
	"Food.Street.X.File":re.compile(r"먹거리 X파일"),
	"Movie.Stalker":re.compile(r"무비\s?스토커"),
	"What.Are.You.Listening.to.Today":re.compile(r"오늘\s?뭐\s?듣지"),
	"Sunnys.FM.Date.Viewable.Radio":re.compile(r"써니의 FM데이트 보이는 라디오"),
	"Merchant.Kim.Man.Deok":re.compile(r"거상(\(巨商\))?\s김만덕"),
	"Golden.Bride":re.compile(r"황금신부"),
	"Evasive.Inquiry.Agency":re.compile(r"얼렁뚱땅 흥신소"),
	"Super.Idol":re.compile(r"슈퍼 아이돌"),
	"The.Legend":re.compile(r"태왕사신기"),
	"Prosecutor.Princess":re.compile(r"검사 프린세스"),
	"Ojakgyo.Brothers":re.compile(r"오작교 형제들"),
	"Youth.FC.Hungry.Eleven":re.compile(r"청춘FC 헝그리 일레븐"),
	"Heir":re.compile(r"후계자"),
	"Dae.Mul":re.compile(r"대물"),
	"Soulmate":re.compile(r"소울메이트"),
	"The.Greatest.Thing.in.the.World":re.compile(r"세상에서 가장 위대한 일"),
	"Cutting.the.Heart":re.compile(r"마음을 자르다"),
	"Style":re.compile(r"스타일[^\s?라이브|\s?포유]"),
	"Auction.House":re.compile(r"옥션\s*하우스"),
	"The.World.That.They.Live.In":re.compile(r"그들이\s?사는\s?세상"),
	"A.Man.Called.God":re.compile(r"신이라 불리운 사나이"),
	"New.Heart":re.compile(r"뉴하트"),
	"Before.and.After.Plastic.Surgery.Clinic":re.compile(r"비포 and 애프터 성형외과"),
	"Soul":re.compile(r"^혼"),
	"9.Ends.2.Outs":re.compile(r"9회말\s*2아웃"),
	"Personal.Preference":re.compile(r"개인의 취향"),
	"Ja.Myung.Go":re.compile(r"자명고"),
	"Dong.Yi":re.compile(r"^동이"),
	"White.Tower":re.compile(r"하얀\s*거탑"),
	"Temptation":re.compile(r"^유혹"),
	"Korea.Peninsula":re.compile(r"한반도"),
	"Case.Number.113":re.compile(r"사건번호 113"),
	"Mothers.Choice":re.compile(r"엄마의 선택"),
	"Love.in.Heaven":re.compile(r"하늘이시여"),
#	"HDTV.Literature":re.compile(r"HDTV 문학관"),
	"Changup.Star":re.compile(r"창업스타"),
	"8.Days.Myster.of.Jeong.Jo.Assassination":re.compile(r"정조암살미스터리 8일"),
	"Moms.Dead.Upset":re.compile(r"엄마가\s?뿔났다"),
	"The.Scale.of.Providence":re.compile(r"신의 저울"),
	"Virtue":re.compile(r"덕이"),
	"Fairy.and.Swindler":re.compile(r"선녀와 사기꾼"),
	"Happy.Time.Last.Scandal":re.compile(r"내생애\s?마지막\s?스캔들"),
	"Thirty.Thousand.Miles.in.Search.of.My.Son":re.compile(r"아들찾아 삼만리"),
	"Stranger.Than.Paradise":re.compile(r"천국보다 낯선"),
	"1001.Nights":re.compile(r"천일야화"),
	"18.vs.29":re.compile(r"열여덟\s?스물아홉"),
	"Tokyo.Shower":re.compile(r"도쿄 여우비"),
	"Wonderful.Days":re.compile(r"참 좋은 시절"),
	"TV.Time.Travel":re.compile(r"시간을 달리는 TV"),
	"Scholar.Who.Walks.The.Night":re.compile(r"밤을 걷는 선비"),
	"Flower.Boy.Ramyun.Shop":re.compile(r"꽃미남 라면가게"),
	"The.Servant":re.compile(r"TV 방자전"),
	"Suspicious.Housekeeper":re.compile(r"수상한 가정부"),
	"Ghost":re.compile(r"유령"),
	"EXID.Showtime":re.compile(r"EXID의?\s?쇼타임"),
	"Ghost.Romance.Mimi":re.compile(r"고스트 로맨스 미미"),
	"Killer.Girl.K":re.compile(r"소녀 K"),
	"Hero":re.compile(r"히어로"),
	"Vampire.Idol":re.compile(r"뱀파이어 아이돌"),
	"Smile.Dong.Hae":re.compile(r"웃어라 동해야"),
	"Golden.Rainbow":re.compile(r"황금\s?무지개"),
	"Cruel.City":re.compile(r"무정도시"),
	"Brain":re.compile(r"브레인"),
	"Iris":re.compile(r"아이리스"),
	"Emergency.Couple":re.compile(r"응급남녀"),
	"Miss.Korea":re.compile(r"미스코리아"),
	"Triple":re.compile(r"트리플"),
	#movies start
	"Sisters.on.the.Road":re.compile(r"지금\, 이대로가 좋아요"),
	"Madeleine":re.compile(r"마들렌"),
	"My.Mighty.Princess":re.compile(r"무림여대생"),
	"The.Beast.And.The.Beauty":re.compile(r"야수와미녀"),
	"A.Bittersweet.Life":re.compile(r"달콤한 인생"),
	"Volcano.High":re.compile(r"화산고"),
	#movies end
	"4.Minutes.Video":re.compile(r"포미닛의 비디오"),
	"I.Order.For.You":re.compile(r"당신을 주문합니다"),
	"Love.Marriage":re.compile(r"연애결혼"),
	"Birth.Secret":re.compile(r"출생의 비밀"),
	"I.Am.Still.Loving.You":re.compile(r"사랑해 당신을"),
	"Dont.Ask.Me.About.the.Past":re.compile(r"과거를 묻지 마세요"),
	"Youre.Beautiful":re.compile(r"미남이시네요"),
	"Love.Me.When.You.Can":re.compile(r"있을때\s*잘해"),
	"Recipe.of.Love":re.compile(r"사랑찬가"),
	"Couple.or.Trouble":re.compile(r"환상의 커플"),
	"First.Love.of.a.Royal.Prince":re.compile(r"황태자의 첫사랑"),
	"Gye.Baek":re.compile(r"계백"),
	"Get.Karl.Oh.Soo.Jung":re.compile(r"칼잡이 오수정"),
	"Pilot":re.compile(r"파일럿"),
	"Spotlight":re.compile(r"스포트라이트"),
	"Cannot.Hate.You":re.compile(r"미워도 좋아"),
	"Winter.Bird":re.compile(r"겨울새"),
	"Dinner.Table":re.compile(r"구원의 밥상"), #find proper name
	"Midnight.Diner":re.compile(r"심야식당"),	
	"My.Fair.Lady":re.compile(r"요조숙녀"),
	"Tokyo.Shower":re.compile(r"도쿄 여우비"),
	"Bad.Love":re.compile(r"못된\s*사랑"),
#	"I.Love.You":re.compile(r"^사랑해"),
	"Spring.Days":re.compile(r"봄 날"),
	"The.Boss":re.compile(r"왕초"),
	"Lobbyist":re.compile(r"로비스트"),
	"Dae.Jo.Young":re.compile(r"대조영"),
	"Kimchi.Cheese.Smile":re.compile(r"김치 치즈 스마일"),
	"Coffee.Prince":re.compile(r"커피프린스"),
	"Oh.My.Ghost":re.compile(r"오 나의 귀신님"),
	"Mun.Hee":re.compile(r"문희"),
	"M.Countdown":re.compile(r"M COUNTDOWN"),
	"I.am.Sam":re.compile(r"아이엠 샘"),
	"She.is.Nineteen":re.compile(r"형수님은 열아홉"),
	"Miss.Kim.Makes.1.Million":re.compile(r"파란만장 미스김 10억만들기"),
	"Billie.Jean.Look.at.Me":re.compile(r"빌리진 날 봐요"),
	"Thousand.Years.of.Love":re.compile(r"천년지애"),
	"Into.the.Storm":re.compile(r"폭풍속으로"),
	"Sunshine.of.Love":re.compile(r"햇빛 쏟아지다"),
	"Salt.Doll":re.compile(r"소금인형"),
	"Lovers":re.compile(r"^연인"),
	"Stairway.to.Heaven":re.compile(r"천국의계단"),
	"All.In":re.compile(r"올인"),
	"Global.Sharing.Project":re.compile(r"글로벌나눔 프로젝트"),
	"Funny.World.Quintet":re.compile(r"재밌는 세상구경 오중주"),
	"Life.Court":re.compile(r"이것은 실화다"),
	"Miss.Korea.The.Reality":re.compile(r"미스코리아 더 리얼리티"),
	"A.Gentlemans.Dignity":re.compile(r"신사의 품격"),
	"Global.Husband":re.compile(r"글로벌 남편백서 내편\,? 남편"),
	"Hello.China":re.compile(r"헬로 차이나"),
	"One.Well.Raised.Daugther":re.compile(r"잘키운 딸 하나"),
	"The.Person.I.Love":re.compile(r"사랑하는\s*사람아"),
	"The.Great.Ambition":re.compile(r"대망"),
	"When.a.Man.Loves.a.Woman":re.compile(r"남자가 사랑할때"),
	"Beauty.Bible":re.compile(r"뷰티바이블"),
	"Yoomis.Room":re.compile(r"유미의 방"),
	"Snow.Flower":re.compile(r"눈꽃"),
	"Save.the.Last.Dance":re.compile(r"마지막\s?춤은 나와\s?함께"),
	"Tears.of.Diamond":re.compile(r"다이아몬드의 눈물"),
	"All.About.Eve":re.compile(r"이브의 모든것"),	
	"My.Love":re.compile(r"마이 러브"),
	"Sassy.Girl.Choon.Hyang":re.compile(r"쾌걸 춘향"),
	"Oh.Feel.Young":re.compile(r"오\!필승 봉순영"),
	"Lawyers":re.compile(r"변호사들"),
	"HyoYeons.One.Million.Likes":re.compile(r"효연의 백만 라이크"),
	"The.Time.We.Were.Not.In.Love":re.compile(r"너를 사랑한 시간"),
	"The.Genius.Grand.Final":re.compile(r"더 지니어스(\：?\s?그랜드 파이널)?"),
	"Goodbye.Sadness":re.compile(r"슬픔이여안녕"),
	"My.Sweetheart.My.Darling":re.compile(r"어여쁜 당신"),
	"Red.Chair":re.compile(r"빨간의자"),
	"Celebrity.Biography":re.compile(r"셀러브리티 바이오그래피"),
	"AfreecaTV.AOA.Livechatting":re.compile(r"아프리카TV AOA 라이브채팅"),
	"The.Accidental.Couple":re.compile(r"그저\s*바라보다가"),
	"Tree.With.Deep.Roots":re.compile(r"뿌리깊은 나무"),
	"Discovery.of.Love":re.compile(r"연애의 발견"),
	"The.Moon.That.Embraces.The.Sun":re.compile(r"해를 품은 달"),
	"Webdrama":re.compile(r"웹드라마"),
	"The.Concert":re.compile(r"더 콘서트"),
	"Age.of.Warriors":re.compile(r"무인시대"),
	"Her.Secret.Weapon":re.compile(r"비밀병기\s*그녀"),
	"History.Special":re.compile(r"역사스페셜"),
	"Masterchef.Korea":re.compile(r"마스터셰프 코리아"),
	"Glorious.Day":re.compile(r"기분 좋은\s*날"),
	"Only.Love":re.compile(r"사랑만 할래"),
	"My.Mother.is.a.Daughter.In.Law":re.compile(r"어머님은 내 며느리"),
	"I.Remember.You":re.compile(r"너를 기억해"),
	"Top.10.Songs":re.compile(r"가요 TOP 10"),
	"I.am.also.Film.Director":re.compile(r"나도 영화 감독이다"),
	"My.Beautiful.Bride":re.compile(r"아름다운 나의\s*신부"),
	"Boarding.House.24":re.compile("하숙24번지"),
	"Whats.Up.Fox":re.compile(r"여우야 뭐하니"),
	"Bodyguard":re.compile(r"보디가드"),
	"Golden.Time":re.compile(r"골든\s*타임"),
	"Yi.San":re.compile(r"이산"),
	"My.Daughter.Seo.Young":re.compile(r"내 딸 서영이"),
	"Temptation.of.Wife":re.compile(r"아내의 유혹"),
	"Jewel.in.the.Palace":re.compile(r"대장금"),
	"School.1":re.compile(r"학교\s*1"),
	"Sunflower":re.compile(r"해바라기"),
	"Goodbye.My.Love":re.compile(r"안녕\s*내사랑"),
	"Robber":re.compile(r"불한당"),
	"The.Princess.Man":re.compile(r"공주의 남자"),
	"See.and.See.Again":re.compile(r"보고 또 보고"),
	"Fight":re.compile(r"맞짱"),
	"Hidden.Identity":re.compile(r"신분을 숨겨라"),
	"King.Geunchogo":re.compile(r"근초고왕"),
	"The.Great.Wives":re.compile(r"위대한 조강지처"),
	"Medical.Brothers":re.compile(r"의가형제"),
	"Brilliant.Legacy":re.compile(r"찬란한 유산"),
	"Hidden.Singer":re.compile(r"히든\s?싱어"),
	"King.And.Queen":re.compile(r"왕과\s*비"),
	"It.Was.Love":re.compile(r"사랑했나봐"),
#	"My.Fair.Lady":re.compile(r"아가씨를 부탁해"),
	"Full.House":re.compile(r"풀하우스"),
	"Hometown.Legends":re.compile(r"전설의 고향"),
	"Romance":re.compile(r"^로망스"),
	"Again":re.compile(r"^어게인"),
	"Papa":re.compile(r"파파"),
	"Three.Guys.and.Three.Girls":re.compile(r"남자셋\,여자셋"),
	"Im.Kkeok.Jung":re.compile(r"임꺽정"),
	"Inside.SuperRace":re.compile(r"인사이드 슈퍼레이스"),
	"Restaurant.of.100.Years":re.compile(r"백년식당"),
	"Girlfriend.Look.After.Our.Dog":re.compile(r"여자친구! 강아지를 부탁해"),
	"Death.Debate":re.compile(r"사망토론"),
	"Let.Me.In":re.compile(r"Let 미인"),
#	"Love.Letter":re.compile(r"리얼로망스 연애편지"),
	"The.5th.Republic":re.compile(r"제5공화국"),
	"The.4th.Republic":re.compile(r"제4공화국"),
	"Sunny.Days.of.Youth":re.compile(r"젊은이의 양지"),
	"HIT.Homicide.Investigation.Team":re.compile(r"히트"),
	"Oh.Ja.Ryong.is.Coming":re.compile(r"오자룡이 간다"),
	"Great.Recipe":re.compile(r"대단한 레시피"),
	"The.Return.of.Hwang.Geum.Bok":re.compile(r"돌아온 황금복"),
	"High.Society":re.compile(r"상류사회"),
	"Angels.Revenge":re.compile(r"천상여자"),
	"Famous.Princesses":re.compile(r"소문난\.*칠공주"),
	"Alone.in.Love":re.compile(r"연애시대"),
	"Pasta":re.compile(r"파스타"),
	"Life.is.Beautiful":re.compile(r"인생은 아름다워"),
	"The.Last.Game":re.compile(r"마지막승부"),
	"Bokbulbok.Show":re.compile(r"복불복 쇼"),
	"Golden.Tower":re.compile(r"황금거탑"),
	"The.Greatest.Love":re.compile(r"^최고의 사랑"),
	"Autumn.in.My.Heart":re.compile(r"가을동화"),
	"Huh.Joon":re.compile(r"허준"),
	"Horse.Doctor":re.compile(r"^마의"),
#	"Big":re.compile(r"^빅"),
	"Comedy.Stations":re.compile(r"웃음 충전소"),
	"Chuno":re.compile(r"추노"),
#	"Goong":re.compile(r"^궁"),
	"Feelings":re.compile(r"느낌"),
	"God.of.Study":re.compile(r"공부의 신"),
	"Love.in.your.Bosom":re.compile(r"사랑을 그대품안에"),
	"The.3rd.Republic":re.compile(r"제\s*3공화국"),
	"MBC.Best.Theater":re.compile(r"베스트\s*극장"),
	"The.Chaser":re.compile(r"추적자"),
	"Pumpkin.Seed":re.compile(r"호박씨"),
	"Match":re.compile(r"^짝"),
	"Chok.Chok.Oppas":re.compile(r"촉촉한 오빠들"),
	"White.Swan":re.compile(r"화이트 스완"),
	"Suspicious.Dog.Cafe":re.compile(r"수상한 애견카페"),
	"Korean.Music.Festival":re.compile(r"국악한마당"),
	"Oh.Halmae":re.compile(r"농촌드라마 오 할매"),
	"Dream.Concert":re.compile(r"드림콘서트"),
	"Assorted.Gems":re.compile(r"보석 비빔밥"),
	"Tempted.Again":re.compile(r"탐나는\s*도다"),
	"Myung.Wol.the.Spy":re.compile(r"스파이 명월"),
	"Beloved.Eun.Dong":re.compile(r"사랑하는 은동아"),
	"49.Days":re.compile(r"49일"),
	"High.Kick.Through.The.Roof":re.compile(r"지붕 뚫고 하이킥"),
	"Capital.Scandal":re.compile(r"경성\s?스캔들"),
	"Protect.the.Boss":re.compile(r"보스를 지켜라"),
	"Emperor.Wang.Gun":re.compile(r"태조\s*왕건"),
	"The.Voice.Of.Korea":re.compile(r"보이스 코리아"),
	"Air.City":re.compile(r"에어시티"),
	"Lie.to.Me":re.compile(r"내게 거짓말을 해봐"),
	"A.Mans.Story":re.compile(r"남자 이야기"),
	"Hong.Gil.Dong":re.compile(r"쾌도 홍길동"),
	"Cheongdamdong.Alice":re.compile(r"청담동 앨리스"),
	"Mask":re.compile(r"가면"),
	"Sungkyunkwan.Scandal":re.compile(r"성균관 스캔들"),
	"The.Woman.Who.Still.Wants.To.Marry":re.compile(r"아직도 결혼하고 싶은 여자"),
	"Royal.Family":re.compile(r"로열 패밀리"),
	"The.God.of.Music":re.compile(r"음악의 신"),
	"The.51st.BaekSang.Arts.Awards":re.compile(r"제51회 백상예술대상"),
	"New.Tales.of.Gisaeng":re.compile(r"신기생뎐"),
	"Blue.Mist":re.compile(r"푸른\s*안개"),
	"City.Hunter":re.compile(r"시티헌터"),
	"Ruby.Ring":re.compile(r"루비반지"),
	"7th.Grade.Civil.Servant":re.compile(r"7급 공무원"),
	"Queen.of.Reversals":re.compile(r"역전의 여왕"),
	"Haeundae.Lovers":re.compile(r"해운대 연인들"),
	"Endless.Love":re.compile(r"끝없는 사랑"),
	"Miss.Daegu.Competition":re.compile(r"미스 대구 선발대회"),
	"Snow.White":re.compile(r"백설공주"),
	"You.Are.My.Destiny":re.compile(r"너는 내 운명"),
#	"Ireland":re.compile(r"아일랜드"),
	"Man.Of.Honor":re.compile(r"영광의 재인"),
	"First.Love":re.compile(r"^첫사랑"),
	"Mary.Stayed.Out.All.Night":re.compile(r"매리는 외박중"),
	"Successful.Story.of.a.Bright.Girl":re.compile(r"명랑소녀( 성공기)*"),
	"The.King.2.Hearts":re.compile(r"더 킹 투\s*하츠"),
	"Queen.of.Ambition":re.compile(r"야왕"),
	#"Faith":re.compile(r"신의"),
	"Mr.Baek.The.Homemade.Food.Master":re.compile(r"집밥\s*백선생"),
	"House.of.10":re.compile(r"모델하우스"),
	"5Days.of.Summer":re.compile(r"5일간의 썸머"),
	"Korean.Food.War":re.compile(r"한식대첩"),
	"Masked.Prosecutor":re.compile(r"복면검사"),
	"Fox.and.Cotton.Candy":re.compile(r"여우와\s*솜사탕"),
	"Eyes.of.Dawn":re.compile(r"여명의 눈동자"),
	"The.Birth.of.the.Rich":re.compile(r"부자의\s*탄생"),
	"The.Painter.of.the.Wind":re.compile(r"바람의 화원"),
	"Dr.Jin":re.compile(r"닥터 진"),
	"Eves.Love":re.compile(r"이브의 사랑"),
	"A.Daughter.Just.Like.You":re.compile(r"딱 너\s*같은 딸"),
	"Running":re.compile(r"심장이\s*뛴다"),
	"Ruler.of.your.own.World":re.compile(r"네\s*멋대로\s*해라"),
	"Surgeon.Bong.Dal.Hee":re.compile(r"외과의사\s*봉달희"),
	"Producer":re.compile(r"프로듀사"),
	"Orange.Marmalade":re.compile(r"오렌지 마말레이드"),
	"Why.Cant.We.Stop.Them":re.compile(r"웬만해선 그들을 막을 수 없다"),
	"Warm.And.Cozy":re.compile(r"맨도롱\s*또(똣|돗)"),
	"Protect.the.Family":re.compile(r"가족을 지켜라"),
	"Improvisation":re.compile(r"순발력"),
	"Playful.Kiss":re.compile(r"장난스런키스"),
	"Lady.Action":re.compile(r"레이디 액션"),
	"Secret.Angel":re.compile(r"비밀천사"),
	"Reckless.Challenge":re.compile(r"무모한도전"),
	"Ex.Girlfriend.Club":re.compile(r"구여친클럽"),
	"K-Star.Report":re.compile(r"한류스타 리포트"),
	"Rediscovery.of.Immortal.Song":re.compile(r"불후의 재발견"),
#	"Asia.Prism":re.compile(r"아시아 프리즘"),
	"My.Sunshine":re.compile(r"마이 선샤인"),
	"Sixteen":re.compile(r"식스틴"),
	"Cool.Kkadang":re.compile(r"쿨까당"),
	"Birds.Dont.Cry":re.compile(r"울지 않는 새"),
	"Good.Life":re.compile(r"통일준비 생활백서 잘 살아보세"),
	"Police.Station":re.compile(r"경찰청 사람들"),
	"KimJaeDongs.Talk.To.You":re.compile(r"김제동의 톡투유"),
	"Seventeen.Project":re.compile(r"세븐틴 프로젝트"),
#	"Music.Video.Bank":re.compile(r"뮤비뱅크"),
	"Slimmy.Lunch.Box":re.compile(r"날씬한\s*도시락"),
	"The.Brave.Teenagers":re.compile(r"고교10대천왕"),
	"The.Lawyers.of.the.Great.Republic.Korea":re.compile(r"대\~한민국 변호사"),
	"Bachelor.While.on.a.Date":re.compile(r"총각 연애하다"),
	"I.Introduce.My.Father":re.compile(r"아빠를 소개합니다"),
	"Go.Go.With.Unnie":re.compile(r"언니랑 고고"),
	"Gu.Family.Book":re.compile(r"구가의 서"),
	"Who.Are.You.School.2015":re.compile(r"후아유(-|\s){1,3}학교 2015"),
	"More.Charming.By.The.Day":re.compile(r"볼수록 애교만점"),
	"Sandglass":re.compile(r"모래시계"),
	"My.Rosy.Life":re.compile(r"장미빛 인생"),
	"1.VS.100":re.compile(r"1 대 100"),
	"Mom.Is.Watching":re.compile(r"엄마가 보고있다"),
	"Moonshine":re.compile(r"문샤인"),
	"Heart.A.Tag":re.compile(r"하트어택"),
	"Nympho.Island":re.compile(r"색녀도"),
	"Love.Switch":re.compile(r"러브스위치"),
	"K-Pop.Star":re.compile(r"케이팝스타"),
	"Divorce.Lawyer.in.Love":re.compile(r"이혼변호사는 연애중"),
	"A.Look.At.Myself":re.compile(r"나를 돌아봐"),
	"The.Three.Musketeers":re.compile(r"해외걸작드라마 삼총사"),
	"Make.a.Woman.Cry":re.compile(r"여자를 울려"),
	"Hilarious.Housewives":re.compile(r"태희혜교지현이"),
	"Catch.Music.if.you.can":re.compile(r"캐치 뮤직 이프 유 캔"),
	"Talkshow.Parents":re.compile(r"토크쇼 부모"),
#	"Mask.King":re.compile(r"복면가왕"),
	"MiSaGo":re.compile(r"두근두근 감동카메라 미사고"),
	"The.Body.Show":re.compile(r"더 바디쇼"),
	"Open.Up":re.compile(r"맴을 열어봐"),
	"My.Unfortunate.Boyfriend":re.compile(r"나의 유감스러운 남자친구"),
	"Splendid.Politics":re.compile(r"화정"),
	"Style.For.You":re.compile(r"스타일 포유"),
	"Exciting.India":re.compile(r"두근두근 인도"),
	"Mother.Person":re.compile(r"엄마사람"),
	"Dancing.9":re.compile(r"댄싱9"),
	"The.Superman.Age":re.compile(r"초인시대"),
	#drama
	"Hair.Day":re.compile(r"머리 심는 날"),
	"Funny.Girl":re.compile(r"웃기는 여자"),
	"Mr.Back":re.compile(r"미스터 백"),
	"Pinocchio":re.compile(r"피노키오"),
	"The.Kings.Face":re.compile(r"왕의 얼굴"),
	"Cheongdamdong.Scandal":re.compile(r"청담동 스캔들"),
	"Make.a.Wish":re.compile(r"소원을 말해봐"),
	"Lady.of.the.Storm":re.compile(r"폭풍의 여자"),
	"Healer":re.compile(r"힐러"),
	"Family.Secrets":re.compile(r"가족의 비밀"),
	"Punch":re.compile(r"펀치|때려"),
	"Sunam.Girls.High.School.Detectives":re.compile(r"선암여고\s*탐정단"),
	"Valid.Love":re.compile(r"일리\s*있는 사랑"),
	"Pride.and.Prejudice":re.compile(r"오만과 편견"),
	"Tears.of.Heaven":re.compile(r"천국의 눈물"),
	"What.happens.to.my.Family":re.compile(r"가족끼리 왜 이래"),
	"Rosy.Lovers":re.compile(r"장미빛 연인들"),
	"The.Legend.of.the.Witch":re.compile(r"전설의 마녀"),
	"Dr.Frost":re.compile(r"닥터 프로스트"),
#	"Misaeng":re.compile(r"미생"),	
	"Misaengmul":re.compile(r"미생물"),
	"Birth.of.a.Beauty":re.compile(r"미녀의\s*탄생"),
	"Best.Wedding":re.compile(r"최고의 결혼"),
	"Apgujeong.Midnight.Sun":re.compile(r"압구정 백야"),
	"Maids":re.compile(r"하녀들"),
	"Modern.Farmer":re.compile(r"모던파머"),
	"Secret.Door":re.compile(r"비밀의 문"),
	"Bad.Guys":re.compile(r"나쁜 녀석들"),
	"Hometown.over.the.hill":re.compile(r"산너머 남촌에는 2"),
	"Tomorrow.Cantabile":re.compile(r"내일도 칸타빌레"),
	"Liar.Game":re.compile(r"라이어게임"),
	"Queen.of.Housewives":re.compile(r"내조의 여왕"),
	"Love.and.Secret":re.compile(r"달콤한 비밀"),
	"You.are.the.only.one":re.compile(r"당신만이 내사랑"),
	"Run.Jang.Mi":re.compile(r"달려라 장미"),
	"Abiding.Love.Dandelion":re.compile(r"TV소설 일편단심 민들레"),
	"Powerful.Opponents":re.compile(r"강적들"),
	"Ok.Family":re.compile(r"옥이네"),
	"Sharp":re.compile(r"반올림"),
	"Sense.King":re.compile(r"눈치왕"),
	"The.Family.is.coming":re.compile(r"떴다 패밀리"),
	"Special.Crimes.Force":re.compile(r"특수사건전담반"),
	"April.Kiss":re.compile(r"4월의\s*키스"),
	"Iron.Lady.Cha":re.compile(r"불굴의 차여사"),
	"Enchanting.Neighbor":re.compile(r"황홀한 이웃"),
	"Mackerel.Run":re.compile(r"달려라 고등어"),
	"Me.Too.Flower":re.compile(r"나도, 꽃!"),
	"Swallow.the.Sun":re.compile(r"태양을[\.|\s]?삼켜라"),
	"My.Husband.got.a.Family":re.compile(r"넝쿨째 굴러온 당신"), 
	"The.Invisible.Man":re.compile(r"투명인간"),
	"Kill.Me.Heal.Me":re.compile(r"킬미,* 힐미"),
	"New.Nonstop":re.compile(r"뉴논스톱"),
	"Hello.My.Teacher":re.compile(r"건빵선생과 별사탕"),
	"I.Need.Romance":re.compile(r"로맨스가 필요해"),
#	"Spy":re.compile(r"스파이"),
	"The.Sons.of.Sol.Pharmacy.House":re.compile(r"솔약국집아들들"),
	"Heart.to.Heart":re.compile(r"하트\s*투\s*하트"),
	"Perseverance.Goo.Hae.Ra":re.compile(r"칠전팔기 구해라"),
	"Wish.Upon.a.Star":re.compile(r"별은 내가슴에"),
	"Shoot.for.the.Star":re.compile(r"별을\s*쏘다"),
#	"Tomato":re.compile(r"토마토"),
	"That.Winter.the.Wind.Blows":re.compile(r"그\s*겨울 바람이 분다"),
	"Crazy.For.You":re.compile(r"사랑에 미치다"),
	"Full.House":re.compile(r"풀하우스"),
	"Smile.You":re.compile(r"그대 웃어요"),
	"Honest.Living":re.compile(r"똑바로 살아라"),
	"Gods.Quiz":re.compile(r"신의 퀴즈"),
	"A.Love.To.Kill":re.compile(r"이\s*죽일놈의\s*사랑"),
	"The.Man.Who.Cant.Get.Married":re.compile(r"결혼 못하는 남자"),
	"Mom.Has.Grown.Horns":re.compile(r"엄마가 뿔났다"),
	"My.Heart.is.Twinkling":re.compile(r"내 마음 반짝반짝"),
	"My.Mans.Woman":re.compile(r"내 남자의 여자"),
	"Vampire.Prosecutor":re.compile(r"뱀파이어\s?검사"),
	"Beethoven.Virus":re.compile(r"베토벤 바이러스"),
	"School.4":re.compile(r"학교4"),
	"Witch.Amusement":re.compile(r"마녀유희"),
	"Basketball":re.compile(r"빠스껫볼"),
	"Shine.Or.Go.Crazy":re.compile(r"빛나거나 미치거나"),
	"Reply.1994":re.compile(r"응답하라 1994"),
	"Shark":re.compile(r"상어"),
	"Lovers.in.Paris":re.compile(r"파리의 연인"),
	"Empire.of.Gold":re.compile(r"황금의 제국"),
	"Queen.Seon.Deok":re.compile(r"선덕여왕"),
	"The.Immortal.Lee.Soon.Shin":re.compile(r"불멸의 이순신"),
	"Hyde.Jekyll.Me":re.compile(r"하이드 지킬\,* 나"),
	"Beating.Heart":re.compile(r"떨리는 가슴"),
	"Dream.High":re.compile(r"드림하이"),
	"Bridal.Mask":re.compile(r"각시탈"),
	"Familys.Honor":re.compile(r"가문의 영광"),
	"Gap.Dong":re.compile(r"갑동이"),
	"Brave.Family":re.compile(r"용감한\s*가족"),
	"City.of.the.Sun":re.compile(r"태양의 도시"),
	"You.have.fallen.for.me":re.compile(r"넌 내게 반했어"),
	"Fool.For.You":re.compile(r"호구의 사랑"),
	"Thank.You.Son":re.compile(r"고맙다 아들아"),
	"Incarnation.Of.Money":re.compile(r"남자의 자격"),
	"Jingbirok":re.compile(r"징비록"),
	"Blood":re.compile(r"블러드"),
	"Flirty.Boy.And.Girl":re.compile(r"썸남썸녀"),
	"Cupid.Factory":re.compile(r"큐피드 팩토리"),
	"Came.to.Me.and.Became.a.Star":re.compile(r"나에게로 와서 별이 되었다"),
	"Bluebirds.House":re.compile(r"파랑새의 집"),
	"Life.Tracker.Lee.Jae.Goo":re.compile(r"인생추적자 이재구"),
	"Heard.It.Through.the.Grapevine":re.compile(r"풍문으로 들었소"),
	"Unkind.Women":re.compile(r"착하지 않은 여자들"),
	"Snowy.Road":re.compile(r"눈길"),
	"TV.Novel.On.a.Blue.Day":re.compile(r"TV소설 그래도 푸르른 날에"),
	"Super.Daddy.Yeol":re.compile(r"슈퍼대디 열"),
	"Flower.of.the.Queen":re.compile(r"여왕의 꽃"),
	"Stay.Still":re.compile(r"가만히 있으라"),
	"Angry.Mom":re.compile(r"앵그리맘"),
	"A.Great.Story":re.compile(r"위대한 이야기"),
	"The.Wind.Blows.In.The.Direction.Of.Hope":re.compile(r"바람은 소망하는 곳으로 분다"),
	"Missing.Noir.M":re.compile(r"실종\s*느와르.*M"),
	"Falling.For.Innocence":re.compile(r"순정에 반하다"), #prev Genuine.Love
	"The.Lover":re.compile(r"더 러버"),
	"Flower.Boys.Next.Door":re.compile(r"이웃집 꽃미남"),
	"Love.From.Today":re.compile(r"오늘부터 사랑해"),
	"Lets.Eat.With.My.Friend":re.compile(r"내친구와\s?식샤를\s?합시다"),
#	"Lets.Eat":re.compile(r"식샤를\s*합시다"),
	#ent
	"Superstar.K6":re.compile(r"슈퍼스타K"),
	"Hello.Stranger":re.compile(r"헬로 이방인"),
	"Happy.Together":re.compile(r"해피\s*투게더"),
	"Oh.My.Baby":re.compile(r"오(\!)* 마이 베이비"),
	"Witch.Hunt":re.compile(r"마녀사냥"),
	"Infinity.Challenge":re.compile(r"무한도전"),
	"We.Got.Married":re.compile(r"우리\s?결혼했어요"),
	"Music.Core":re.compile(r"(쇼!)*\s*음악중심"),
	"3.Meals.a.Day":re.compile(r"삼시세끼"),
	"Star.Married.Couple":re.compile(r"자기야\-*\s*백년손님"),
	"A.very.curious.story":re.compile(r"아궁이"),
	"Cook.King.Korea":re.compile(r"쿡킹 코리아"),
	"World.Changing.Quiz":re.compile(r"세바퀴(.+?VS[^\.]+)?"),
	"Super.Idol.Chartshow":re.compile(r"슈퍼 아이돌 차트쇼"),
	"Song.Festival":re.compile(r"가요대축제"),
	"Entertainment.Awards":re.compile(r"연예대상"),
	"Always.Cantare":re.compile(r"언제나 칸타레"),
	"Cartalk.Show.S.":re.compile(r"카톡쇼 S"),
	"Cartalk.Show.X.":re.compile(r"카톡쇼 X"),
	"My.Bodys.Usage.Manual":re.compile(r"내 몸 사용 설명서"),
	"Lets.go.to.School":re.compile(r"학교\s*다녀오겠습니다"),
	"Love.Unification.of.South.Man.and.North.Women":re.compile(r"(애정통일 )*남남북녀"),
	"My.young.Tutor":re.compile(r"띠동갑내기 과외하기"),
	"Law.of.the.Jungle":re.compile(r"(김병만의 )?정글의 법칙"),
#	"Law.of.the.Jungle.in.Brazil":re.compile(r"정글의 법칙 in 브라질"),
#	"Law.of.the.Jungle.in.Indian.Ocean":re.compile(r"정글의 법칙 in 인도양"),
	"Inkigayo":re.compile(r"인기가요"),
	"Star.King":re.compile(r"놀라운 대회 스타\!?킹"),
	"Actresses.Secret.Travel.in":re.compile(r"여우 비행 인"),
	"Good.Sunday.K-Pop.Star":re.compile(r"(일요일이 좋다-)*K팝스타"),
	"Good.Sunday.Running.Man":re.compile(r"(일요일이 좋다\s*-\s*)*런닝맨"),
#	"Good.Sunday.Survival.Audition.K-Pop.Star":re.compile(r"일요일이 좋다-서바이벌 오디션 K팝스타"),
	"The.Return.of.Superman":re.compile(r"슈퍼맨이 돌아왔다"),
#	"Our.Sunday.Night.King.of.Masked.Singers":re.compile(r"일밤 1부 복면가왕"),
	"Our.Sunday.Night.Daddy.Where.Are.You.Going":re.compile(r"(일밤 1부 )*아빠\!* 어디가"),
	"Our.Sunday.Night.Real.Man":re.compile(r"(일밤 2부 )*진짜\s*사나이"),
	"Our.Sunday.Night.Animals":re.compile(r"일밤 1부 애니멀즈"),
#	"Saturday.Freedom.Immortal.Music":re.compile(r"불후의 명곡 전설을 노래하다"),
	"Happy.Sunday.2Days.1Night":re.compile(r"(해피\s*선데이\s*-\s*)*1박2일"),
	"Comedy.Big.League":re.compile(r"코미디\s*빅리그"),
	"Smile.People":re.compile(r"웃음을 찾는 사람들"),
	"Gag.Concert":re.compile(r"개그콘서트"),
	"I.Live.Alone":re.compile(r"나 혼자 산다"),
	"SuperJuniorM.Guest.House":re.compile(r"슈퍼주니어M 게스트하우스"),
	"Lets.Go.Dream.Team":re.compile(r"출발\s*드림팀"),
	"Extreme.Surprise":re.compile(r"익스트림 서프라이즈"),
	"Mysterious.TV.Surprise":re.compile(r"신비한TV 서프라이즈"),
	"Concert.7080":re.compile(r"(배철수의 )*콘서트\s*7080"),
	"Salon.de.raison":re.compile(r"속사정\s*쌀롱"),
	"Take.Care.of.the.Fridge":re.compile(r"냉장고를\s*부탁해"),
	"Abnormal.Summit":re.compile(r"비정상회담"),
	"Hello.Counselor":re.compile(r"(대국민 토크쇼 )*안녕하세요"),
	"Healing.Camp":re.compile(r"힐링캠프( 기쁘지 아니한가)*"),
	"Safety.First":re.compile(r"위기탈출 넘버원"),
	"Golden.Egg":re.compile(r"고수의 비법 황금알"),
	"Trot.Festival":re.compile(r"트로트 대축제"),
	"National.Song.Contest":re.compile(r"전국노래자랑"),
	"Master.of.Life":re.compile(r"생활의 달인"),
	"True.Justice":re.compile(r"정의본색"),
	"Now.on.my.way.to.meet.you":re.compile(r"이제 만나러\s*갑니다"),
	"100.Song":re.compile(r"백인백곡 끝까지 간다"),
	"9.Store":re.compile(r"살림9단의 만물상"),
	"Today.Menu":re.compile(r"오늘\s*뭐\s*먹지"),
	"Talk.Show.Dongchimi":re.compile(r"속풀이쇼 동치미"),
	"Medical.Recipeshow.Atlas":re.compile(r"메디컬 레시피쇼 아틀라스"),
	"With.You.S02.The.Greatest.Love":re.compile(r"님과 함께 시즌2 최고의 사랑"),
	"Drama.Awards":re.compile(r"연기대상"),
	"Daechan.Life":re.compile(r"대찬인생"),
	"Cool.Kiz.on.the.Block":re.compile(r"우리동네\s?예체능"),
	"After.School.Bokbulbok":re.compile(r"방과후 복불복"),
	"Music.Festival":re.compile(r"가요대제전"),
	"The.4th.Weekly.Idol.Awards":re.compile(r"제4회.주간아이돌 어워즈"),
	"New.Years.Eve.Concert.Creating.Hope.Korea":re.compile(r"새해맞이 음악회 희망창조, 코리아"),
	"Wedding.Story":re.compile(r"결혼 이야기"),
	"War.Of.The.Words":re.compile(r"썰전"),
	"Power.to.Children":re.compile(r"아이에게 권력을"),
	"I.have.a.Gods.Body":re.compile(r"나는 몸신이다( 베스트)*"),
	"Capture.the.Moment.How.is.that.possible":re.compile(r"순간포착 세상에 이런일이"),
	"Music.Bank":re.compile(r"뮤직뱅크"),
	"YooHeeYeols.Sketchbook":re.compile(r"유희열의 스케치북"),
	"Talk.with.Star.in.Taxi":re.compile(r"현장토크쇼 (택시|TAXI)"),
	"Future.Predictions.Variety.Butterfly.Effect":re.compile(r"미래예측 버라이어티 나비효과"),
	"Sweden.Laundry":re.compile(r"스웨덴 세탁소"),
	"I.love.Movie":re.compile(r"영화가 좋다"),
	"Movieworld":re.compile(r"접속! 무비월드"),
	"Entertainment.Weekly":re.compile(r"연예가\s*중계"),
	"The.Human.Condition":re.compile(r"인간의 조건"),
	"Start.Video.Tour":re.compile(r"출발! 비디오 여행"),
	"Star.Junior.Show":re.compile(r"스타주니어쇼 붕어빵"),
	"TV.Zoo":re.compile(r"TV 동물농장"),
	"Find.Delicious.TV":re.compile(r"찾아라!\s*맛있는 TV"),
	"Vienna.Philharmonic.Orchestra.New.Years.Concert":re.compile(r"비엔나 필하모닉 오케스트라 신년음악회"),
	"Section.TV":re.compile(r"섹션TV 연예통신"),
	"Gourmet.Road":re.compile(r"식신로드"),
	"Top.Gear.Korea":re.compile(r"탑\s*기어 코리아"),
	"Yaman.TV":re.compile(r"야만TV"),
	"Roommate":re.compile("룸메이트"),
	"Lord.of.the.Thumb":re.compile(r"엄지의 제왕"),
	"Gayo.Stage":re.compile(r"가요무대"),
	"Birth.of.a.Mother":re.compile(r"엄마의 탄생"),
	"Vitamin":re.compile(r"비타민"),
	"Golden.Fishery":re.compile(r"(황금어장)?\-?\s?라디오\s?스타"),
	"Eco.Village":re.compile(r"에코빌리지 즐거운 가"),
	"Secret.Love":re.compile(r"비밀연애"),
	"Kids.are.Lifes.Blessing":re.compile(r"유자식\s*상팔자"),
	"Live.Entertainment.Weekly":re.compile(r"한밤의 TV연예"),
	"M.Countdown.Begins":re.compile(r"엠카운트다운 비긴즈"),
	"Accused.by.Kang.Yong.Suk":re.compile(r"강용석의 고소한"),
	"Weekly.Idol":re.compile(r"주간\s*아이돌"),
	"Baby.100Years.Guests":re.compile(r"자기야 - 백년손님"),
	"Sistar.Showtime":re.compile(r"씨스타의\s*쇼타임"),
	"Turn.to.the.King":re.compile(r"켠김에 왕까지"),
	"Determined.to.Watch.the.Premiere":re.compile(r"작정하고 본방사수"),
	"Hyung.Don.Dae.Joons.Hit.Machine":re.compile(r"형돈이와 대준이의 히트제조기"),
	"King.of.Idol":re.compile(r"아이돌의\s*제왕"),
	"Who.is.the.Better.Magician":re.compile(r"누가 누가 잘하나"),
	"Open.Concert":re.compile(r"열린음악회"),
	"Global.Request.Show.A.Song.For.You":re.compile(r"글로벌 리퀘스트 쇼 어송포유"),
	"Doctors.Warning":re.compile(r"닥터의 경고"),
	"Shopper.Man":re.compile(r"나르는 쇼퍼맨"),
	"Cheeky.Interview.4Things.Show":re.compile(r"발칙한 인터뷰 4가지 쇼"),
	"Revealing.a.List.of.Names":re.compile(r"명단공개"),
	"Showtime.Burning.the.Beast":re.compile(r"쇼타임\-버닝더비스트"),
	"We.Got.Married.Kwanghee.Sunhwa":re.compile(r"광희 선화 결혼이야기"),
	"We.Got.Married.SonNaeun.Taemin":re.compile(r"우결-손나은,태민"),
	"We.Got.Married.Junhee.Jinwoon":re.compile(r"고준희 진운 결혼이야기"),
	"We.Got.Married.Eunjung.Jangwoo":re.compile(r"은정 장우"),
	"Star.News":re.compile(r"스타뉴스"),
	"Tasty.Road":re.compile(r"테이스티 로드"),
	"Dissecting.Entertainment.The.Women.Trio":re.compile(r"연예 해부 여기자 삼총사가 간다"),
	"The.Demand.Of.Luxurious.Food":re.compile(r"수요미식회"),
	"The.29th.Golden.Disk.Awards.in.Beijing":re.compile(r"제29회 골든디스크 어워즈 인 베이징"),
	"The.24th.Seoul.Music.Awards":re.compile(r"제24회 하이원 서울가요대상"),
	"MTV.The.Show":re.compile(r"더\s*쇼"),
	"A.Celebrity.Lives.In.Our.House":re.compile(r"우리집에 연예인이 산다"),
	"Style.Live":re.compile(r"스타일 라이브"),
	"Olive.Show":re.compile(r"올리브쇼"),
	"Brave.Reporters":re.compile(r"용감한 기자들"),
	"Please.Permit":re.compile(r"허락해 주세요"),
	"Culture.Bigbang.The.Concert.Of.Yoon.Gun":re.compile(r"문화빅뱅 윤건의 더 콘서트"),
	"A.Skill.Of.Wisdom.Cane":re.compile(r"지혜의 한 수 회초리"),
	"Jung.Yonghwas.Hologram":re.compile(r"정용화의\s*홀로그램"),
	"Unpretty.Rapstar":re.compile(r"언프리티\s*랩스타"),
	"I.Am.A.Singer":re.compile(r"나는 가수다"),
	"Dating.Alone":re.compile(r"나홀로 연애중"),
	"TV.Law.Firm":re.compile(r"TV로펌 법대법"),
	"Ultimate.Quiz.Show.Q":re.compile(r"최강연승 퀴즈쇼 큐"),
	"Space.Sympathy":re.compile(r"스페이스 공감"),
	"Where.is.my.Friends.Home":re.compile(r"내\s*친구의\s*집은\s*어디인가"),
	"My.Little.Television":re.compile(r"마이\s*리틀\s*텔(레|리)비전|마리텔|MLT-1\d( -)?"),
	"Independent.Cinema":re.compile(r"독립영화관"),
	"Car.Center":re.compile(r"카(\!)*센터"),
	"Saturday.Night.Live.Korea":re.compile(r"(SNL|snl)\s*코리아"),
	"VIXX.One.Fine.Day":re.compile(r"빅스의 어느 멋진날"),
	"AOA.One.Fine.Day":re.compile(r"AOA\s*어느\s*멋진날"),
	"Girls.Day.One.Fine.Day":re.compile(r"걸스데이의 어느 멋진 날"),
	"Shin.Dong.Yups.Bachelor.Party":re.compile(r"신동엽과 총각파티"),
	"Romantic.Show.Yesterday":re.compile(r"낭만쇼 예스터데이"),
	"The.Golden.Bell.Challenge":re.compile(r"도전 골든벨"),
	"Star.Golden.Bell":re.compile(r"스타 골든벨"),
	"Code.Zero":re.compile(r"코드제로"),
	"Challenge.1000.Songs":re.compile(r"도전 1000곡"),
	"A.Dinner.Of.Fisherman":re.compile(r"어부의\s*만찬"),
	"Burning.Youth":re.compile(r"불타는 청춘"),
	"Mystery.Music.Show.Mask.King":re.compile(r"(미스터리 음악쇼 )*복면가왕"),
	"Tiger.Mask.Magic.Show":re.compile(r"타이거 마스크 매직쇼"),
	"Return.To.Farming.Project":re.compile(r"귀농프로젝트"),
	"Idolstar.Championship":re.compile(r"아이돌스타 선수권대회"),
	"Idolstar.Futsal.Archery.Athletics.Basketball.Championship":re.compile(r"아이돌스타 육상 농구 풋살 양궁 선수권\s*대회"),
	"Running.Toward.Tomorrow":re.compile(r"내일을 향해 뛰어라"),
	"Noisy.Animal.Theater":re.compile(r"와글와글 동물극장"),
	"Take.Care.of.Dad":re.compile(r"(일요일이 좋다-)?아빠를 부탁해"),
	"Infinite.Challenger":re.compile(r"토요일 토요일은 무도다"),
	"Kim.Jae.Dongs.Talk.To.You.Dont.You.Worry":re.compile(r"김제동의 톡투유 걱정 말아요 그대"),
	"Saturday.Is.For.Singers":re.compile(r"(토요일! 토요일은 가수다|토토가)"),
	"Yeongjae.Balguldan":re.compile(r"영재\s*발굴단"),
	"LeeSeungHwan.Concert.Jinjja":re.compile(r"이승환 콘서트 진짜"),
	"Star.has.2.Job":re.compile(r"스타는 투잡 중"),
	"Our.Home":re.compile(r"우리집"),
	"Love.Data":re.compile(r"러브데이터"),
	"Romance.of.the.Week":re.compile(r"로맨스의 일주일"),
	"Absolute.Man":re.compile(r"절대남자"),
	"Witch.and.Beast":re.compile(r"마녀와 야수"),
	"Network.Special.Choice":re.compile(r"네트워크\s?특선"),
	"Comedy.Road":re.compile(r"코미디의 길"),
	"Marriage.Busters":re.compile(r"결혼 터는 남자들"),
	"Sisters.Choice":re.compile(r"언니들의 선택"),
	"Show.Champion":re.compile(r"쇼 챔피언"),
	"Stardust":re.compile(r"스타더스트 뮤비뱅크"),
	"I.See.Your.Voice":re.compile(r"너의\s*목소리가\s*보여"),
	"Problematic.Man":re.compile(r"문제적 남자"),
	"The.Secrets.of.Nature":re.compile(r"천기누설"),
	"Picnic.Live":re.compile(r"피크닉 라이브 소풍"),
	"Gagman.KimYoungCheols.Shameless.Travel.English.With.Deeva.Jessica":re.compile(r"개그맨 김영철의 뻔뻔한 여행영어 with 디바제시카\(Deeva Jessica\)"),
	"Match.Made.In.Heaven.Returns":re.compile(r"천생연분\.*\s*리턴즈"),
	"How.About.Tonight":re.compile(r"오늘밤 어때"),
	"Little.Big.Hero":re.compile(r"리틀빅 히어로"),
	"Delicious.Guys":re.compile(r"맛있는\s*녀석들"),
	"Sonamoos.Pet.House":re.compile(r"소나무의 펫하우스"),
	"One.Night.Study":re.compile(r"원나잇 스터디"),
	"Same.Bed.Different.Drama":re.compile(r"동상이몽\,?\s?괜찮아\s?괜찮아"),
	"Grandpas.over.Flowers":re.compile(r"꽃보다 할배"),
	"Show.Me.The.Money":re.compile(r"쇼미더머니|SHOW ME THE MONEY"),
	"The.Girl.Who.Sees.Smell":re.compile(r"냄새를\s*보는\s*소녀"),
	"Crime.Scene":re.compile(r"크라임\s*씬"),
	"The.Bunker":re.compile(r"더 벙커"),
	# HDTV Feature
	"The.Hard.Goodbye":re.compile(r"내가 살았던 집"),
	"The.Post.Horse.Curse":re.compile(r"역마"),
	"The.Outdoor.Lamp":re.compile(r"외등"),
	"Sad.to.be.Forgotten":re.compile(r"서러워라\,* 잊혀진다는 것은"),
	"Saeya.Saeya":re.compile(r"새야새야"),
	"The.Buckwheat.Season":re.compile(r"메밀꽃\s*필\s*무렵"),
	"The.Last.Song":re.compile(r"노래여 마지막 노래여"),
	"Moon.Altar":re.compile(r"달의제단"),
	"Castella":re.compile(r"카스테라"),
	"My.Bloody.Valentine":re.compile(r"나의 피투성이 연인"),
	"Deungsinbul":re.compile(r"등신불"),
	"Sonaki":re.compile(r"소나기"),
	"Who.murdered.Kurt.Cobain":re.compile(r"누가 커트코베인을 죽였는가"),
	"Bad.Story":re.compile(r"나쁜소설"),
	"Way.To.Sampo":re.compile(r"삼포 가는 길"),
	"The.Flag":re.compile(r"깃발"),
}
